threads:
  hisat2_build: 4
  hisat2_align: 8
  samtools_view: 4
  samtools_fixmate: 4
  samtools_sort: 4
  samtools_markdup: 4
  samtools_consensus: 4

query_dir: "Query"

samples:
  S1: "S1_r1.fastq.gz"
  S2: "S2_r1.fastq.gz"
  S3: ["S3_r1.fastq.gz", "S3_r2.fastq.gz"]

reference: "Genome/ref.fa"
